<?php
require_once dirname(dirname(dirname(__FILE__))) . '/auth/session.php';
require_once dirname(dirname(dirname(__FILE__))) . '/config/config.php';
require_once dirname(dirname(dirname(__FILE__))) . '/config/database.php';
require_once dirname(dirname(dirname(__FILE__))) . '/config/functions.php';

requireLogin();
requirePermission('temp_employees.view', 'view');

$activeMenu = 'temp_employees';

// ── Company settings ──────────────────────────────────────────
$cs          = getCompanySettings();
$companyName = $cs['company_name'] ?? 'HR';

// ── Parameters ────────────────────────────────────────────────
$projectId = (int)($_GET['project'] ?? 0);
$siteId    = (int)($_GET['site']    ?? 0);
$fromRaw   = trim($_GET['from']     ?? '');

// Snap to Monday of the chosen (or current) week
if ($fromRaw && preg_match('/^\d{4}-\d{2}-\d{2}$/', $fromRaw)) {
    $fromTs = strtotime($fromRaw);
} else {
    $fromTs = strtotime('monday this week');
}
$dow    = (int)date('N', $fromTs);  // 1=Mon … 7=Sun
$fromTs -= ($dow - 1) * 86400;
$from   = date('Y-m-d', $fromTs);
$to     = date('Y-m-d', $fromTs + 6 * 86400);

// Build 7-day column definitions
$days = [];
for ($i = 0; $i < 7; $i++) {
    $ts     = $fromTs + $i * 86400;
    $days[] = ['ts' => $ts, 'short' => date('D', $ts), 'date' => date('d M', $ts), 'ymd' => date('Y-m-d', $ts)];
}

// ── Projects list ─────────────────────────────────────────────
$projects = db()->query("SELECT id, name, code FROM temp_projects ORDER BY name")->fetchAll();

// ── Project details & sites ───────────────────────────────────
$projectRow      = null;
$sitesForProject = [];
if ($projectId) {
    $stP = db()->prepare("SELECT id, name, code FROM temp_projects WHERE id = ?");
    $stP->execute([$projectId]);
    $projectRow = $stP->fetch();

    $stS = db()->prepare("SELECT id, name FROM temp_sites WHERE project_id = ? ORDER BY name");
    $stS->execute([$projectId]);
    $sitesForProject = $stS->fetchAll();
}

// ── Helper: build employee query ──────────────────────────────
function buildEmpQuery(int $projectId, int $siteId): array {
    $where  = ["te.project_id = ?", "te.status = 'active'"];
    $params = [$projectId];
    if ($siteId) { $where[] = 'te.site_id = ?'; $params[] = $siteId; }
    return [implode(' AND ', $where), $params];
}

// ── Excel export (before HTML) ────────────────────────────────
if ($projectId && isset($_GET['export']) && $_GET['export'] === 'excel') {
    [$empSQL, $empParams] = buildEmpQuery($projectId, $siteId);

    $stE = db()->prepare("
        SELECT te.employee_number, te.first_name, te.last_name,
               te.position_title, te.rate_type, te.attendance_method,
               ts.name AS site_name
        FROM temp_employees te
        LEFT JOIN temp_sites ts ON ts.id = te.site_id
        WHERE $empSQL
        ORDER BY ts.name, te.last_name, te.first_name
    ");
    $stE->execute($empParams);
    $employees = $stE->fetchAll();

    $projectCode = $projectRow['code'] ?? 'PROJ';
    $siteLabel   = '';
    if ($siteId) {
        foreach ($sitesForProject as $s) {
            if ($s['id'] == $siteId) { $siteLabel = ' — ' . $s['name']; break; }
        }
    }

    header('Content-Type: application/vnd.ms-excel; charset=utf-8');
    header('Content-Disposition: attachment; filename="timesheet_' . $projectCode . '_' . $from . '.xls"');
    echo "\xEF\xBB\xBF";

    // Meta
    echo $companyName . "\n";
    echo "Weekly Attendance Timesheet\n";
    echo "Project:\t" . ($projectRow ? $projectRow['code'] . ' — ' . $projectRow['name'] : '') . $siteLabel . "\n";
    echo "Week:\t" . date('d M Y', $fromTs) . ' to ' . date('d M Y', $fromTs + 6 * 86400) . "\n";
    echo "Generated:\t" . date('d M Y H:i') . "\t\tGenerated by:\t" . ($_SESSION['user_name'] ?? '') . "\n\n";

    // Header row
    $header = ['#', 'Emp. No.', 'Full Name', 'Position', 'Site', 'Attendance Method'];
    foreach ($days as $d) {
        $header[] = $d['short'] . ' ' . $d['date'] . ' (In)';
        $header[] = $d['short'] . ' ' . $d['date'] . ' (Out)';
        $header[] = $d['short'] . ' ' . $d['date'] . ' (Hrs)';
    }
    array_push($header, 'Total Hours', 'Remarks', 'Supervisor Signature');
    echo implode("\t", $header) . "\n";

    $n = 1;
    foreach ($employees as $emp) {
        $row = [
            $n++,
            $emp['employee_number'],
            trim($emp['first_name'] . ' ' . $emp['last_name']),
            $emp['position_title'] ?? '',
            $emp['site_name']      ?? '',
            ucfirst($emp['attendance_method'] ?? ''),
        ];
        for ($i = 0; $i < 7; $i++) {
            $row[] = '';   // In
            $row[] = '';   // Out
            $row[] = '';   // Hrs
        }
        array_push($row, '', '', '');  // Total, Remarks, Signature
        echo implode("\t", $row) . "\n";
    }

    // Footer
    echo "\n\nSupervisor Name: ________________\tSignature: ________________\tDate: ________________\n";
    echo "\n" . $companyName . " — Confidential — Generated " . date('d M Y') . "\n";
    exit;
}

// ── Employees for print preview ───────────────────────────────
$employees = [];
if ($projectId) {
    [$empSQL, $empParams] = buildEmpQuery($projectId, $siteId);
    $stE = db()->prepare("
        SELECT te.employee_number, te.first_name, te.last_name,
               te.position_title, te.rate_type, te.attendance_method,
               ts.name AS site_name
        FROM temp_employees te
        LEFT JOIN temp_sites ts ON ts.id = te.site_id
        WHERE $empSQL
        ORDER BY ts.name, te.last_name, te.first_name
    ");
    $stE->execute($empParams);
    $employees = $stE->fetchAll();
}

// Column count for colspan helpers
$totalCols = 5 + (7 * 2) + 2; // fixed(5) + days(14) + trailing(2)

$pageTitle = 'Weekly Timesheet';
require_once dirname(dirname(dirname(__FILE__))) . '/includes/header.php';
?>

<style>
/* Screen styles */
.ts-table { width: 100%; border-collapse: collapse; font-size: 0.78rem; min-width: 900px; }
.ts-table th {
    background: #023852; color: #fff;
    padding: 5px 5px; text-align: center;
    font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.03em;
    border: 1px solid #01293d; vertical-align: middle; white-space: nowrap;
}
.ts-table th.left-align { text-align: left; }
.ts-table td {
    padding: 6px 5px; border: 1px solid #dee2e6;
    vertical-align: middle; white-space: nowrap;
}
.ts-table tbody tr:hover td { background: #f8fafc; }
.ts-table .site-row td {
    background: #eef2f7; font-size: 0.73rem;
    font-weight: 600; color: #023852;
    padding: 4px 8px; white-space: normal;
}
.ts-table .blank-cell { min-width: 54px; }

/* Print styles */
@media print {
    .no-print { display: none !important; }
    .print-only { display: block !important; }
    .ts-table { font-size: 7.5px; }
    .ts-table th { font-size: 6.5px; padding: 3px 3px; }
    .ts-table td { font-size: 7.5px; padding: 5px 3px; }
    .ts-table .blank-cell { min-width: 40px; }
    body, .main-content, .content-wrapper { padding: 0 !important; margin: 0 !important; }
    @page { size: A4 landscape; margin: 8mm; }
}
@media screen { .print-only { display: none; } }
</style>

<!-- Page header (no-print) -->
<div class="page-header d-flex align-items-center justify-content-between flex-wrap gap-2 mb-4 no-print">
    <div>
        <h1 class="page-title mb-0">Weekly Timesheet</h1>
        <p class="text-muted small mb-0">Printable manual attendance sheet — fill in clock-in / clock-out by hand</p>
    </div>
    <div style="display:flex;gap:8px;">
        <?php if (canEdit('temp_employees.edit')): ?>
        <a href="<?= APP_URL ?>/modules/temp_employees/attendance_entry.php<?= $projectId ? '?project=' . $projectId . ($siteId ? '&site=' . $siteId : '') : '' ?>" class="btn btn-primary btn-sm">
            Enter Attendance Digitally
        </a>
        <?php endif; ?>
        <a href="<?= APP_URL ?>/modules/temp_employees/index.php" class="btn btn-outline-secondary btn-sm">
            <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 18 9 12 15 6"/></svg>
            Back to Temp Employees
        </a>
    </div>
</div>

<!-- Filter form (no-print) -->
<div class="card border-0 shadow-sm mb-4 no-print">
    <div class="card-body py-3">
        <form method="GET" id="tsForm" class="row g-2 align-items-end">
            <div class="col-12 col-md-3">
                <label class="form-label form-label-sm fw-semibold">
                    Project <span class="text-danger">*</span>
                </label>
                <select name="project" class="form-select form-select-sm" id="projectSel" required>
                    <option value="">— Select Project —</option>
                    <?php foreach ($projects as $p): ?>
                    <option value="<?= $p['id'] ?>" <?= $projectId == $p['id'] ? 'selected' : '' ?>>
                        <?= e($p['code']) ?> — <?= e($p['name']) ?>
                    </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <?php if ($sitesForProject): ?>
            <div class="col-12 col-md-2">
                <label class="form-label form-label-sm fw-semibold">Site</label>
                <select name="site" class="form-select form-select-sm">
                    <option value="">All Sites</option>
                    <?php foreach ($sitesForProject as $s): ?>
                    <option value="<?= $s['id'] ?>" <?= $siteId == $s['id'] ? 'selected' : '' ?>>
                        <?= e($s['name']) ?>
                    </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <?php else: ?>
            <input type="hidden" name="site" value="">
            <?php endif; ?>
            <div class="col-12 col-md-2">
                <label class="form-label form-label-sm fw-semibold">Week of</label>
                <input type="date" name="from" class="form-control form-control-sm" value="<?= $from ?>">
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary btn-sm">Generate</button>
            </div>
            <?php if ($projectId && $employees): ?>
            <div class="col-auto">
                <a href="?project=<?= $projectId ?>&site=<?= $siteId ?>&from=<?= $from ?>&export=excel"
                   class="btn btn-outline-secondary btn-sm" title="Download Excel timesheet">
                    <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>
                    Excel
                </a>
            </div>
            <div class="col-auto">
                <button type="button" class="btn btn-outline-secondary btn-sm" onclick="window.print()" title="Print / Save as PDF">
                    <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect x="6" y="14" width="12" height="8"/></svg>
                    Print / PDF
                </button>
            </div>
            <?php endif; ?>
        </form>
    </div>
</div>

<?php if ($projectId && $employees): ?>

<!-- Week navigation (no-print) -->
<div class="d-flex justify-content-between align-items-center mb-3 no-print">
    <a href="?project=<?= $projectId ?>&site=<?= $siteId ?>&from=<?= date('Y-m-d', $fromTs - 7 * 86400) ?>"
       class="btn btn-outline-secondary btn-sm">
        <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 18 9 12 15 6"/></svg>
        Prev Week
    </a>
    <span class="fw-semibold" style="font-size:0.88rem;">
        <?= date('D d M Y', $fromTs) ?> &nbsp;–&nbsp; <?= date('D d M Y', $fromTs + 6 * 86400) ?>
    </span>
    <a href="?project=<?= $projectId ?>&site=<?= $siteId ?>&from=<?= date('Y-m-d', $fromTs + 7 * 86400) ?>"
       class="btn btn-outline-secondary btn-sm">
        Next Week
        <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="9 18 15 12 9 6"/></svg>
    </a>
</div>

<!-- ── Print header (visible only when printing) ───────────── -->
<div class="print-only" style="border-bottom:2px solid #023852;padding-bottom:8px;margin-bottom:10px;">
    <div style="display:flex;justify-content:space-between;align-items:flex-start;">
        <div>
            <div style="font-size:14px;font-weight:700;color:#023852;"><?= e($companyName) ?></div>
            <div style="font-size:11px;font-weight:600;margin-top:2px;">Weekly Attendance Timesheet</div>
            <div style="font-size:9px;color:#444;margin-top:3px;">
                Project: <strong><?= e($projectRow['code'] . ' — ' . $projectRow['name']) ?></strong>
                <?php if ($siteId): ?>
                <?php foreach ($sitesForProject as $s): if ($s['id'] == $siteId): ?>
                &nbsp;|&nbsp; Site: <strong><?= e($s['name']) ?></strong>
                <?php endif; endforeach; ?>
                <?php endif; ?>
            </div>
            <div style="font-size:9px;color:#444;margin-top:2px;">
                Week: <strong><?= date('D d M Y', $fromTs) ?> – <?= date('D d M Y', $fromTs + 6 * 86400) ?></strong>
            </div>
        </div>
        <div style="text-align:right;font-size:8px;color:#555;">
            <div>Total employees: <strong><?= count($employees) ?></strong></div>
            <div style="margin-top:2px;">Generated: <?= date('d M Y H:i') ?></div>
            <div style="margin-top:10px;border-top:1px solid #ccc;padding-top:8px;">
                Supervisor: ________________________
            </div>
            <div style="margin-top:4px;">Signature: ________________________</div>
            <div style="margin-top:4px;">Date: ________________________</div>
        </div>
    </div>
</div>

<!-- ── Browser-only info card ──────────────────────────────── -->
<div class="card border-0 shadow-sm mb-3 no-print">
    <div class="card-body py-2 px-3 d-flex align-items-center justify-content-between flex-wrap gap-2">
        <div>
            <span class="fw-semibold"><?= e($projectRow['code'] . ' — ' . $projectRow['name']) ?></span>
            <span class="badge bg-primary ms-2" style="font-size:0.72rem;"><?= count($employees) ?> employee<?= count($employees) != 1 ? 's' : '' ?></span>
        </div>
        <span class="text-muted small">Active employees only · All attendance methods</span>
    </div>
</div>

<!-- ── Timesheet table ─────────────────────────────────────── -->
<div style="overflow-x:auto;">
<table class="ts-table">
    <thead>
        <tr>
            <th class="left-align" rowspan="2" style="width:28px;">#</th>
            <th class="left-align" rowspan="2" style="min-width:80px;">Emp. No.</th>
            <th class="left-align" rowspan="2" style="min-width:110px;">Full Name</th>
            <th class="left-align" rowspan="2" style="min-width:90px;">Position</th>
            <th class="left-align" rowspan="2" style="min-width:80px;">Site</th>
            <?php foreach ($days as $d): ?>
            <th colspan="2" style="background:#034a6e;">
                <?= $d['short'] ?><br>
                <span style="font-weight:400;font-size:0.65rem;"><?= $d['date'] ?></span>
            </th>
            <?php endforeach; ?>
            <th rowspan="2" style="min-width:52px;">Total<br>Hours</th>
            <th rowspan="2" style="min-width:80px;">Remarks</th>
        </tr>
        <tr>
            <?php foreach ($days as $d): ?>
            <th style="font-size:0.63rem;background:#045880;">In</th>
            <th style="font-size:0.63rem;background:#045880;">Out</th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $n        = 1;
        $lastSite = '__NONE__';
        foreach ($employees as $emp):
            $siteName = $emp['site_name'] ?? 'Unassigned';
            if ($siteName !== $lastSite):
                $lastSite = $siteName;
        ?>
        <tr class="site-row">
            <td colspan="<?= $totalCols ?>">
                <svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="margin-right:4px;"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>
                Site: <?= e($siteName) ?>
            </td>
        </tr>
        <?php endif; ?>
        <tr>
            <td style="text-align:center;color:#aaa;font-size:0.72rem;"><?= $n++ ?></td>
            <td style="font-size:0.75rem;color:#555;"><?= e($emp['employee_number']) ?></td>
            <td><?= e($emp['first_name'] . ' ' . $emp['last_name']) ?></td>
            <td style="color:#555;font-size:0.75rem;"><?= e($emp['position_title'] ?? '') ?></td>
            <td style="color:#555;font-size:0.75rem;"><?= e($siteName) ?></td>
            <?php for ($i = 0; $i < 7; $i++): ?>
            <td class="blank-cell">&nbsp;</td>
            <td class="blank-cell">&nbsp;</td>
            <?php endfor; ?>
            <td class="blank-cell">&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>

<!-- ── Print footer ────────────────────────────────────────── -->
<div class="print-only" style="margin-top:14px;font-size:7px;color:#aaa;text-align:center;border-top:1px solid #eee;padding-top:6px;">
    <?= e($companyName) ?> &mdash; Weekly Attendance Timesheet &mdash; Confidential &mdash; <?= date('d M Y') ?>
</div>

<?php elseif ($projectId && !$employees): ?>
<div class="alert alert-info">
    No active employees found for this project<?= $siteId ? ' / site' : '' ?>.
    Check that employees are set to <em>Active</em> status.
</div>

<?php else: ?>
<!-- Prompt to choose project -->
<div class="card border-0 shadow-sm">
    <div class="card-body text-center py-5">
        <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" viewBox="0 0 24 24" fill="none"
             stroke="currentColor" stroke-width="1.2" class="text-muted mb-3" style="opacity:.35;">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
            <polyline points="14 2 14 8 20 8"/>
            <line x1="16" y1="13" x2="8" y2="13"/>
            <line x1="16" y1="17" x2="8" y2="17"/>
            <line x1="10" y1="9" x2="8" y2="9"/>
        </svg>
        <p class="text-muted mb-1 fw-semibold">Select a project to generate a timesheet</p>
        <p class="text-muted small">Choose the project above, optionally filter by site and week, then click <strong>Generate</strong>.</p>
    </div>
</div>
<?php endif; ?>

<?php require_once dirname(dirname(dirname(__FILE__))) . '/includes/footer.php'; ?>
