<?php
require_once dirname(dirname(__DIR__)) . '/auth/session.php';
require_once dirname(dirname(__DIR__)) . '/config/config.php';
require_once dirname(dirname(__DIR__)) . '/config/database.php';
require_once dirname(dirname(__DIR__)) . '/config/functions.php';

requireLogin();

if (!hasPermission('activity_log.view', 'export')) {
    auditLog('security', 'access_denied', null, null, null,
        "Role '" . ($_SESSION['user_role'] ?? 'unknown') . "' denied: activity_log.view.export at " . ($_SERVER['REQUEST_URI'] ?? ''));
    http_response_code(403);
    exit('Access denied.');
}

$export   = $_GET['export']   ?? '';   // 'user' | 'category'
$type     = $_GET['type']     ?? '';   // 'admin' | 'employee' | 'temp' | 'consultant' | 'all'
$id       = (int)($_GET['id'] ?? 0);
$dateFrom = $_GET['from'] ?? '2000-01-01';
$dateTo   = $_GET['to']   ?? date('Y-m-d');

$dfFull = $dateFrom . ' 00:00:00';
$dtFull = $dateTo   . ' 23:59:59';

$companyName = db()->query("SELECT value FROM settings WHERE `key`='company_name' LIMIT 1")->fetchColumn() ?: 'Komagin HR';
$generatedAt = date('Y-m-d H:i:s');
$generatedBy = $_SESSION['user_name'] ?? 'Super Admin';

// ── Helper: send CSV headers ───────────────────────────────────────────────
function csvStart(string $filename): void {
    header('Content-Type: text/csv; charset=UTF-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: no-cache, no-store, must-revalidate');
    echo "\xEF\xBB\xBF"; // UTF-8 BOM for Excel
}

function csvRow(array $cols): void {
    $escaped = array_map(function($v) {
        $v = str_replace('"', '""', (string)$v);
        return '"' . $v . '"';
    }, $cols);
    echo implode(',', $escaped) . "\r\n";
}

function csvMeta(string $company, string $title, string $from, string $to, string $by, string $at): void {
    csvRow([$company . ' — ' . $title]);
    csvRow(['Generated by', $by]);
    csvRow(['Generated at', $at]);
    csvRow(['Date range', $from . ' to ' . $to]);
    csvRow([]);
}

// ══════════════════════════════════════════════════════════════════════
// INDIVIDUAL USER EXPORT
// ══════════════════════════════════════════════════════════════════════
if ($export === 'user') {

    if ($type === 'admin') {
        $row = db()->prepare("SELECT u.*,
            COALESCE(e.first_name, u.first_name) AS disp_first,
            COALESCE(e.last_name,  u.last_name)  AS disp_last
            FROM users u LEFT JOIN employees e ON e.id = u.employee_id WHERE u.id = ?");
        $row->execute([$id]);
        $subject = $row->fetch(PDO::FETCH_ASSOC);
        if (!$subject) exit('User not found.');

        $name = trim(($subject['disp_first']??'').' '.($subject['disp_last']??'')) ?: $subject['username'];

        $stmt = db()->prepare("SELECT * FROM audit_logs WHERE user_id=? ORDER BY created_at DESC");
        $stmt->execute([$id]);
        $logs = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $filename = 'activity_' . preg_replace('/[^a-z0-9]+/i', '_', $name) . '_' . date('Ymd') . '.csv';
        csvStart($filename);
        csvMeta($companyName, 'Activity Log — ' . $name, 'All time', date('Y-m-d'), $generatedBy, $generatedAt);
        csvRow(['#','Date/Time','User','Role','Module','Action','Record ID','Before','After','Reason','IP Address','User Agent']);
        foreach ($logs as $i => $log) {
            csvRow([
                $i+1,
                $log['created_at'],
                $log['user_name'],
                strtoupper($subject['role']),
                $log['module'],
                $log['action'],
                $log['record_id'] ?? '',
                $log['old_value'] ?? '',
                $log['new_value'] ?? '',
                $log['reason'] ?? '',
                $log['ip_address'] ?? '',
                $log['user_agent'] ?? '',
            ]);
        }
        exit;

    } elseif ($type === 'employee') {
        $row = db()->prepare("SELECT e.*, u.id AS user_id, u.username, u.role
            FROM employees e LEFT JOIN users u ON u.employee_id = e.id WHERE e.id = ?");
        $row->execute([$id]);
        $subject = $row->fetch(PDO::FETCH_ASSOC);
        if (!$subject) exit('Employee not found.');

        $name = trim($subject['first_name'] . ' ' . $subject['last_name']);
        $filename = 'activity_emp_' . preg_replace('/[^a-z0-9]+/i', '_', $name) . '_' . date('Ymd') . '.csv';
        csvStart($filename);
        csvMeta($companyName, 'Activity Log — Employee: ' . $name, 'All time', date('Y-m-d'), $generatedBy, $generatedAt);

        // Employee profile summary
        csvRow(['EMPLOYEE DETAILS']);
        csvRow(['Name', $name]);
        csvRow(['Employee Number', $subject['employee_number']]);
        csvRow(['Email', $subject['email'] ?? '']);
        csvRow(['Status', ucfirst(str_replace('_', ' ', $subject['status']))]);
        csvRow(['Portal Last Login', $subject['portal_last_login'] ?? 'Never']);
        csvRow([]);

        if ($subject['user_id']) {
            $stmt = db()->prepare("SELECT * FROM audit_logs WHERE user_id=? ORDER BY created_at DESC");
            $stmt->execute([$subject['user_id']]);
            $logs = $stmt->fetchAll(PDO::FETCH_ASSOC);

            csvRow(['ACTION LOG']);
            csvRow(['#','Date/Time','Module','Action','Record ID','Before','After','Reason','IP Address']);
            foreach ($logs as $i => $log) {
                csvRow([
                    $i+1,
                    $log['created_at'],
                    $log['module'],
                    $log['action'],
                    $log['record_id'] ?? '',
                    $log['old_value'] ?? '',
                    $log['new_value'] ?? '',
                    $log['reason'] ?? '',
                    $log['ip_address'] ?? '',
                ]);
            }
        } else {
            csvRow(['No system user account linked. No action log available.']);
        }
        exit;

    } elseif ($type === 'temp') {
        $row = db()->prepare("SELECT * FROM temp_employees WHERE id = ?");
        $row->execute([$id]);
        $subject = $row->fetch(PDO::FETCH_ASSOC);
        if (!$subject) exit('Temp employee not found.');

        $name = trim($subject['first_name'] . ' ' . $subject['last_name']);
        $filename = 'activity_temp_' . preg_replace('/[^a-z0-9]+/i', '_', $name) . '_' . date('Ymd') . '.csv';
        csvStart($filename);
        csvMeta($companyName, 'Activity Log — Temp Employee: ' . $name, 'All time', date('Y-m-d'), $generatedBy, $generatedAt);

        csvRow(['TEMPORARY EMPLOYEE RECORD']);
        csvRow(['Name',             $name]);
        csvRow(['Employee Number',  $subject['employee_number']]);
        csvRow(['Email',            $subject['email'] ?? '']);
        csvRow(['Position',         $subject['position_title'] ?? '']);
        csvRow(['Status',           ucfirst($subject['status'])]);
        csvRow(['Contract Start',   $subject['start_date'] ?? '']);
        csvRow(['Contract End',     $subject['end_date'] ?? '']);
        csvRow([ucfirst($subject['rate_type'] ?? 'daily') . ' Rate', $subject['daily_rate'] !== null ? number_format((float)$subject['daily_rate'], 2) : '']);
        csvRow(['Portal Active',    $subject['portal_active'] ? 'Yes' : 'No']);
        csvRow(['Portal Last Login',$subject['portal_last_login'] ?? 'Never']);
        csvRow(['Notes',            $subject['notes'] ?? '']);
        csvRow(['Created At',       $subject['created_at']]);
        csvRow(['Updated At',       $subject['updated_at']]);
        exit;

    } elseif ($type === 'consultant') {
        $row = db()->prepare("SELECT * FROM consultants WHERE id = ?");
        $row->execute([$id]);
        $subject = $row->fetch(PDO::FETCH_ASSOC);
        if (!$subject) exit('Consultant not found.');

        $name = trim($subject['first_name'] . ' ' . $subject['last_name']);
        $filename = 'activity_consultant_' . preg_replace('/[^a-z0-9]+/i', '_', $name) . '_' . date('Ymd') . '.csv';
        csvStart($filename);
        csvMeta($companyName, 'Activity Log — Consultant: ' . $name, 'All time', date('Y-m-d'), $generatedBy, $generatedAt);

        csvRow(['CONSULTANT DETAILS']);
        csvRow(['Name',               $name]);
        csvRow(['Consultant Number',  $subject['consultant_number']]);
        csvRow(['Email',              $subject['email'] ?? '']);
        csvRow(['Type',               $subject['type'] === 'time_based' ? 'Time-Based' : 'Output-Based']);
        csvRow(['Status',             ucfirst($subject['status'])]);
        csvRow(['Contract Start',     $subject['start_date'] ?? '']);
        csvRow(['Contract End',       $subject['end_date'] ?? '']);
        csvRow(['Portal Last Login',  $subject['portal_last_login'] ?? 'Never']);
        csvRow([]);

        $stmt = db()->prepare("SELECT * FROM consultant_attendance WHERE consultant_id=? ORDER BY work_date DESC, id DESC");
        $stmt->execute([$id]);
        $logs = $stmt->fetchAll(PDO::FETCH_ASSOC);

        csvRow(['ATTENDANCE / SESSION LOG']);
        csvRow(['#','Work Date','Clock In','Break Out','Break In','Clock Out','Total Hours','Notes']);
        foreach ($logs as $i => $log) {
            csvRow([
                $i+1,
                $log['work_date'],
                $log['clock_in']    ? date('Y-m-d H:i:s', strtotime($log['clock_in']))    : '',
                $log['break_start'] ? date('Y-m-d H:i:s', strtotime($log['break_start'])) : '',
                $log['break_end']   ? date('Y-m-d H:i:s', strtotime($log['break_end']))   : '',
                $log['clock_out']   ? date('Y-m-d H:i:s', strtotime($log['clock_out']))   : '',
                $log['total_hours'] !== null ? number_format((float)$log['total_hours'], 2) : '',
                $log['notes'] ?? '',
            ]);
        }
        exit;
    }
}

// ══════════════════════════════════════════════════════════════════════
// CATEGORY / BULK EXPORT
// ══════════════════════════════════════════════════════════════════════
if ($export === 'category') {

    $adminRoles = ['super_admin','hr_manager','hr_officer','hrofficer','payroll_manager',
                   'payroll_officer','finance_viewer','recruitment_officer','training_officer','supervisor'];

    if ($type === 'admin' || $type === 'all') {
        if ($type === 'admin') {
            $filename = 'activity_all_admins_' . date('Ymd') . '.csv';
            csvStart($filename);
            csvMeta($companyName, 'Activity Log — All Admin & HR Users', $dateFrom, $dateTo, $generatedBy, $generatedAt);
        } else {
            // 'all' — we'll stream multiple sections; start file here
            $filename = 'activity_full_export_' . date('Ymd') . '.csv';
            csvStart($filename);
            csvMeta($companyName, 'Complete Activity Export — All Users', $dateFrom, $dateTo, $generatedBy, $generatedAt);
        }

        csvRow(['═══ ADMIN / HR USERS ═══']);
        csvRow(['#','Date/Time','User Name','Username','Role','Module','Action','Record ID','Before','After','Reason','IP Address']);

        $adminRoleIn = implode(',', array_fill(0, count($adminRoles), '?'));
        $stmt = db()->prepare("SELECT a.*, u.username, u.role,
            COALESCE(e.first_name, u.first_name) AS first_name,
            COALESCE(e.last_name, u.last_name)   AS last_name
            FROM audit_logs a
            JOIN users u ON u.id = a.user_id
            LEFT JOIN employees e ON e.id = u.employee_id
            WHERE u.role IN ($adminRoleIn) AND a.created_at BETWEEN ? AND ?
            ORDER BY a.created_at DESC");
        $stmt->execute(array_merge($adminRoles, [$dfFull, $dtFull]));
        $i = 1;
        while ($log = $stmt->fetch(PDO::FETCH_ASSOC)) {
            csvRow([
                $i++,
                $log['created_at'],
                trim(($log['first_name']??'').' '.($log['last_name']??'')) ?: $log['user_name'],
                $log['username'],
                strtoupper($log['role']),
                $log['module'],
                $log['action'],
                $log['record_id'] ?? '',
                $log['old_value'] ?? '',
                $log['new_value'] ?? '',
                $log['reason'] ?? '',
                $log['ip_address'] ?? '',
            ]);
        }
        if ($type === 'admin') { exit; }
        csvRow([]);
    }

    if ($type === 'employees' || $type === 'all') {
        if ($type === 'employees') {
            $filename = 'activity_all_employees_' . date('Ymd') . '.csv';
            csvStart($filename);
            csvMeta($companyName, 'Activity Log — All Employees', $dateFrom, $dateTo, $generatedBy, $generatedAt);
        }

        csvRow(['═══ EMPLOYEES ═══']);
        csvRow(['#','Date/Time','Employee Name','Employee Number','Module','Action','Record ID','Before','After','IP Address']);

        $stmt = db()->prepare("SELECT a.*, e.employee_number,
            e.first_name, e.last_name
            FROM audit_logs a
            JOIN users u ON u.id = a.user_id
            JOIN employees e ON e.id = u.employee_id
            WHERE a.created_at BETWEEN ? AND ?
            ORDER BY e.last_name ASC, a.created_at DESC");
        $stmt->execute([$dfFull, $dtFull]);
        $i = 1;
        while ($log = $stmt->fetch(PDO::FETCH_ASSOC)) {
            csvRow([
                $i++,
                $log['created_at'],
                trim($log['first_name'] . ' ' . $log['last_name']),
                $log['employee_number'],
                $log['module'],
                $log['action'],
                $log['record_id'] ?? '',
                $log['old_value'] ?? '',
                $log['new_value'] ?? '',
                $log['ip_address'] ?? '',
            ]);
        }
        if ($type === 'employees') { exit; }
        csvRow([]);
    }

    if ($type === 'temp' || $type === 'all') {
        if ($type === 'temp') {
            $filename = 'activity_all_temp_' . date('Ymd') . '.csv';
            csvStart($filename);
            csvMeta($companyName, 'Activity Log — All Temporary Employees', $dateFrom, $dateTo, $generatedBy, $generatedAt);
        }

        csvRow(['═══ TEMPORARY EMPLOYEES ═══']);
        csvRow(['#','Name','Employee Number','Position','Status','Contract Start','Contract End','Rate Type','Rate (K)','Portal Active','Last Portal Login','Notes','Created At']);

        $stmt = db()->query("SELECT * FROM temp_employees ORDER BY last_name ASC, first_name ASC");
        $i = 1;
        while ($te = $stmt->fetch(PDO::FETCH_ASSOC)) {
            csvRow([
                $i++,
                trim($te['first_name'] . ' ' . $te['last_name']),
                $te['employee_number'],
                $te['position_title'] ?? '',
                ucfirst($te['status']),
                $te['start_date'] ?? '',
                $te['end_date'] ?? '',
                ucfirst($te['rate_type'] ?? 'daily'),
                $te['daily_rate'] !== null ? number_format((float)$te['daily_rate'], 2) : '',
                $te['portal_active'] ? 'Yes' : 'No',
                $te['portal_last_login'] ?? 'Never',
                $te['notes'] ?? '',
                $te['created_at'],
            ]);
        }
        if ($type === 'temp') { exit; }
        csvRow([]);
    }

    if ($type === 'consultants' || $type === 'all') {
        if ($type === 'consultants') {
            $filename = 'activity_all_consultants_' . date('Ymd') . '.csv';
            csvStart($filename);
            csvMeta($companyName, 'Activity Log — All Consultants', $dateFrom, $dateTo, $generatedBy, $generatedAt);
        }

        csvRow(['═══ CONSULTANTS ═══']);
        csvRow(['#','Date/Time','Consultant Name','Consultant Number','Type','Work Date','Clock In','Break Out','Break In','Clock Out','Total Hours','Notes']);

        $stmt = db()->prepare("SELECT ca.*, c.first_name, c.last_name, c.consultant_number, c.type
            FROM consultant_attendance ca
            JOIN consultants c ON c.id = ca.consultant_id
            WHERE ca.work_date BETWEEN ? AND ?
            ORDER BY c.last_name ASC, ca.work_date DESC");
        $stmt->execute([$dateFrom, $dateTo]);
        $i = 1;
        while ($log = $stmt->fetch(PDO::FETCH_ASSOC)) {
            csvRow([
                $i++,
                $log['created_at'],
                trim($log['first_name'] . ' ' . $log['last_name']),
                $log['consultant_number'],
                $log['type'] === 'time_based' ? 'Time-Based' : 'Output-Based',
                $log['work_date'],
                $log['clock_in']    ? date('Y-m-d H:i:s', strtotime($log['clock_in']))    : '',
                $log['break_start'] ? date('Y-m-d H:i:s', strtotime($log['break_start'])) : '',
                $log['break_end']   ? date('Y-m-d H:i:s', strtotime($log['break_end']))   : '',
                $log['clock_out']   ? date('Y-m-d H:i:s', strtotime($log['clock_out']))   : '',
                $log['total_hours'] !== null ? number_format((float)$log['total_hours'], 2) : '',
                $log['notes'] ?? '',
            ]);
        }
        if ($type === 'consultants') { exit; }
        csvRow([]);
    }

    // Footer for full export
    if ($type === 'all') {
        csvRow([]);
        csvRow(['END OF REPORT — ' . $companyName]);
        csvRow(['This document is for legal reference and internal use only.']);
        csvRow(['Generated at', $generatedAt, 'by', $generatedBy]);
        exit;
    }
}

http_response_code(400);
exit('Invalid export parameters.');
